// Interface automatically generated by schemas-to-ts

import { Application } from '../../../application/content-types/application/application';
import { Application_Plain } from '../../../application/content-types/application/application';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Status {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    status_name: string;
    applications: { data: Application[] };
  };
}
export interface Status_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status_name: string;
  applications: Application_Plain[];
}

export interface Status_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status_name: string;
  applications: number[];
}

export interface Status_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  status_name: string;
  applications: AdminPanelRelationPropertyModification<Application_Plain>;
}
