// Interface automatically generated by schemas-to-ts

import { Status } from '../../../status/content-types/status/status';
import { Direction } from '../../../direction/content-types/direction/direction';
import { Partner } from '../../../partner/content-types/partner/partner';
import { Status_Plain } from '../../../status/content-types/status/status';
import { Direction_Plain } from '../../../direction/content-types/direction/direction';
import { Partner_Plain } from '../../../partner/content-types/partner/partner';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum ApplicationType {
   = 'практика',
   = 'стажировка',}

export interface Application {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    application_type: ApplicationType;
    task_description: string;
    requirements: string;
    number_of_students: number;
    start_date?: Date;
    end_date?: Date;
    paid_internship: boolean;
    results?: string;
    status?: { data: Status };
    direction?: { data: Direction };
    partner?: { data: Partner };
  };
}
export interface Application_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  application_type: ApplicationType;
  task_description: string;
  requirements: string;
  number_of_students: number;
  start_date?: Date;
  end_date?: Date;
  paid_internship: boolean;
  results?: string;
  status?: Status_Plain;
  direction?: Direction_Plain;
  partner?: Partner_Plain;
}

export interface Application_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  application_type: ApplicationType;
  task_description: string;
  requirements: string;
  number_of_students: number;
  start_date?: Date;
  end_date?: Date;
  paid_internship: boolean;
  results?: string;
  status?: number;
  direction?: number;
  partner?: number;
}

export interface Application_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  application_type: ApplicationType;
  task_description: string;
  requirements: string;
  number_of_students: number;
  start_date?: Date;
  end_date?: Date;
  paid_internship: boolean;
  results?: string;
  status?: AdminPanelRelationPropertyModification<Status_Plain>;
  direction?: AdminPanelRelationPropertyModification<Direction_Plain>;
  partner?: AdminPanelRelationPropertyModification<Partner_Plain>;
}
