// Interface automatically generated by schemas-to-ts

import { Group } from '../../../group/content-types/group/group';
import { Application } from '../../../application/content-types/application/application';
import { Group_Plain } from '../../../group/content-types/group/group';
import { Application_Plain } from '../../../application/content-types/application/application';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Direction {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    direction_name: string;
    groups: { data: Group[] };
    applications: { data: Application[] };
  };
}
export interface Direction_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  direction_name: string;
  groups: Group_Plain[];
  applications: Application_Plain[];
}

export interface Direction_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  direction_name: string;
  groups: number[];
  applications: number[];
}

export interface Direction_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  direction_name: string;
  groups: AdminPanelRelationPropertyModification<Group_Plain>;
  applications: AdminPanelRelationPropertyModification<Application_Plain>;
}
