// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { ResponseStatus } from '../../../response-status/content-types/response-status/response-status';
import { Student } from '../../../student/content-types/student/student';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { ResponseStatus_Plain } from '../../../response-status/content-types/response-status/response-status';
import { Student_Plain } from '../../../student/content-types/student/student';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Response {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    cv_file: { data: Media };
    response_status?: { data: ResponseStatus };
    student?: { data: Student };
  };
}
export interface Response_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  cv_file: Media_Plain;
  response_status?: ResponseStatus_Plain;
  student?: Student_Plain;
}

export interface Response_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  cv_file: number;
  response_status?: number;
  student?: number;
}

export interface Response_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  cv_file: AdminPanelRelationPropertyModification<Media_Plain>;
  response_status?: AdminPanelRelationPropertyModification<ResponseStatus_Plain>;
  student?: AdminPanelRelationPropertyModification<Student_Plain>;
}
