// Interface automatically generated by schemas-to-ts

import { Application } from '../../../application/content-types/application/application';
import { Application_Plain } from '../../../application/content-types/application/application';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Partner {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    company_name: string;
    contact_name: string;
    position: string;
    email: string;
    phone_number: string;
    telegram?: string;
    applications: { data: Application[] };
  };
}
export interface Partner_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company_name: string;
  contact_name: string;
  position: string;
  email: string;
  phone_number: string;
  telegram?: string;
  applications: Application_Plain[];
}

export interface Partner_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company_name: string;
  contact_name: string;
  position: string;
  email: string;
  phone_number: string;
  telegram?: string;
  applications: number[];
}

export interface Partner_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company_name: string;
  contact_name: string;
  position: string;
  email: string;
  phone_number: string;
  telegram?: string;
  applications: AdminPanelRelationPropertyModification<Application_Plain>;
}
