// Interface automatically generated by schemas-to-ts

import { Group } from '../../../group/content-types/group/group';
import { Response } from '../../../response/content-types/response/response';
import { Group_Plain } from '../../../group/content-types/group/group';
import { Response_Plain } from '../../../response/content-types/response/response';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Student {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    full_name: string;
    email: string;
    phone_number?: string;
    group?: { data: Group };
    responses: { data: Response[] };
  };
}
export interface Student_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  full_name: string;
  email: string;
  phone_number?: string;
  group?: Group_Plain;
  responses: Response_Plain[];
}

export interface Student_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  full_name: string;
  email: string;
  phone_number?: string;
  group?: number;
  responses: number[];
}

export interface Student_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  full_name: string;
  email: string;
  phone_number?: string;
  group?: AdminPanelRelationPropertyModification<Group_Plain>;
  responses: AdminPanelRelationPropertyModification<Response_Plain>;
}
